### ISSUE TITLE
能不能再win系统上提供http

### ISSUE THREAD

**Issue by a1007479270** [yzqzy/wechat-assistant#1]
使用http网页来操作，这样我可以frp穿透在外面使用微信

**Comment by yzqzy** [comment]
@a1007479270 理论倒是可以支持。

你是想用网站的形式访问这些功能吗？两种思路：

1. 直接部署，不安装应用，网页访问当前功能？
2. 提供 api 接口服务，支持外部直接调用就可以？

**Comment by a1007479270** [comment]
两种都可以的，只要能在外部网络调用，这样可以实现更多的功能

**Comment by yzqzy** [comment]
> 两种都可以的，只要能在外部网络调用，这样可以实现更多的功能

现在就支持外部调用，wx assistant 只是一个客户端。

具体可以看 [wxhelper](https://github.com/ttttupup/wxhelper) ，已有详细 [API 文档](https://github.com/ttttupup/wxhelper/blob/main/doc/3.9.5.81.md)，支持修改端口。

<img width="685" alt="image" src="https://github.com/yzqzy/wechat-assistant/assets/96212026/3d2c753c-2d7b-46b5-892f-a4bd743ba2b5">
