### ISSUE TITLE
任务管理能否增加一个任意消息转发

### ISSUE THREAD

**Issue by a1007479270** [yzqzy/wechat-assistant#2]
实现情况是需要转发收款的消息
触发任务  任意消息

**Comment by yzqzy** [comment]
@a1007479270 收款消息指的是别人转帐给你吗？还是普通文本消息。

任意消息转发是不是可以理解为，监控某个群或者某个人的消息，自动转发给其他人（群）。

**Comment by a1007479270** [comment]
是的，收款消息指的是别人二维码转帐给我的，以http的形式发送给外部网络， 比如发送给n8n自动化，我就可以利用n8n实现更多的功能。当然普通文本消息也可以转发。
例1.收到微信收款商业版的金额消息后以http的形式发送到n8n，n8n执行指定的任务， 直接利用n8n实现自动化记账  ，也可以收款回调实现收款功能
2.监控某个人的任意消息的转发  ，当n8n收到消息后 根据消息内容执行特定的任务，比如收到1后任务1，收到2后执行任务2，

-----------------------------------

**Comment by yzqzy** [comment]
> 是的，收款消息指的是别人二维码转帐给我的，以http的形式发送给外部网络， 比如发送给n8n自动化，我就可以利用n8n实现更多的功能。当然普通文本消息也可以转发。 例1.收到微信收款商业版的金额消息后以http的形式发送到n8n，n8n执行指定的任务， 直接利用n8n实现自动化记账 ，也可以收款回调实现收款功能 2.监控某个人的任意消息的转发 ，当n8n收到消息后 根据消息内容执行特定的任务，比如收到1后任务1，收到2后执行任务2，

最新版本已支持 "消息转发"。
