### ISSUE TITLE
低版本无法登陆如何解决

### ISSUE THREAD

**Issue by hcliu987** [yzqzy/wechat-assistant#20]

**Comment by yzqzy** [comment]
@hcliu987 低版本是指什么？微信低版本还是啥？

**Comment by hcliu987** [comment]
使用你提供的微信版本，扫码登陆提示低版本，需要下载最新的版本

**Comment by yzqzy** [comment]
> 使用你提供的微信版本，扫码登陆提示低版本，需要下载最新的版本

解决办法 [参考 issue](https://github.com/lich0821/WeChatFerry/issues/148)。
