### ISSUE TITLE
【功能建议】转发多条消息到群和群标签

### ISSUE THREAD

**Issue by lwjlwjlwjlwj** [yzqzy/wechat-assistant#21]
群标签：方便一次选中需要的群

**Comment by lwjlwjlwjlwj** [comment]
导入csv或txt来批量选择，是不是实现起来要容易不少

**Comment by yzqzy** [comment]
> 导入csv或txt来批量选择，是不是实现起来要容易不少

差不多，群标签其实更合理一些，有时间再处理下。

**Comment by yzqzy** [comment]
> 导入csv或txt来批量选择，是不是实现起来要容易不少

[wxhelper-3.9.5.81-v14](https://github.com/yzqzy/wechat-assistant/releases/tag/wxhelper-3.9.5.81-v14) 版本已支持上述功能。
