### ISSUE TITLE
微信提示版本低，需升级微信

### ISSUE THREAD

**Issue by unsilence** [yzqzy/wechat-assistant#22]
#### Describe the problem you confuse
使用WeChatSetup 3.9.5.81 扫码登录，微信提示版本低，需升级微信，怎么不强制升级？谢谢

**Comment by yzqzy** [comment]
> #### Describe the problem you confuse
> 使用WeChatSetup 3.9.5.81 扫码登录，微信提示版本低，需升级微信，怎么不强制升级？谢谢

可以试下这个 [过低版本工具](https://github.com/yzqzy/wechat-assistant/releases/download/v0.0.0/low_verison.2.3.exe)。

**Comment by yzqzy** [comment]
> > #### Describe the problem you confuse
> 使用WeChatSetup 3.9.5.81 扫码登录，微信提示版本低，需升级微信，怎么不强制升级？谢谢

3.9.5.81 确实存在这个问题，需要自主解决，[参考 issue](https://github.com/lich0821/WeChatFerry/issues/148)。
或者使用 [3.9.8.25](https://github.com/yzqzy/wechat-assistant/releases/tag/3.9.8.25-v2) 版本，测试没有上述问题。
