### ISSUE TITLE
【功能丢失】新版，群没有办法邀请人了 

### ISSUE THREAD

**Issue by lwjlwjlwjlwj** [yzqzy/wechat-assistant#24]

**Comment by yzqzy** [comment]
新版确实没有这个功能，受限于 [wxhelper](https://github.com/ttttupup/wxhelper/issues/358) 的开源功能。
这个功能只在旧版本中有，旧版本提示更新问题可以参照 [issue](https://github.com/yzqzy/wechat-assistant/issues/22)。
