### ISSUE TITLE
微信 3.9.11.19 运行报错 

### ISSUE THREAD

**Issue by kaka77** [yzqzy/wechat-assistant#28]
运行 wechatsdk_version_API_Launcher_v1.0.3.exe ，设置端口，登录微信后报错！微信自动退出。
<img width="322" alt="企业微信截图_20240709164755" src="https://github.com/yzqzy/wechat-assistant/assets/8677125/d116f4e8-e0cb-4915-bbbb-b676a6941c05">

**Comment by yzqzy** [comment]
> 运行 wechatsdk_version_API_Launcher_v1.0.3.exe ，设置端口，登录微信后报错！微信自动退出。 <img alt="企业微信截图_20240709164755" width="322" src="https://private-user-images.githubusercontent.com/8677125/346888221-d116f4e8-e0cb-4915-bbbb-b676a6941c05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NzMxNzEsIm5iZiI6MTcyMDU3Mjg3MSwicGF0aCI6Ii84Njc3MTI1LzM0Njg4ODIyMS1kMTE2ZjRlOC1lMGNiLTQ5MTUtYmJiYi1iNjc2YTY5NDFjMDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMDA1NDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZmNzUwMzE4Y2UzNjA4ZDViMmViOGRmZmMzYjc4ZGJiMjY3N2QzMDllMjRkZmJkZTIzMDlhMDRhMmViZmQ4YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B684rKnLUTOsGaJ86-YmBjF0QddC-oxjZJHSfwvghpI">

更新了下注入工具版本，可以用 [v1.0.9](https://github.com/yzqzy/wechat-assistant/releases/tag/v0.0.0) 试下。
另外该问题不是微信助手应用问题，可以去 [wechatsdk](https://github.com/WeChatAPIs/wechatAPI) 仓库寻求解决方案。
