### ISSUE TITLE
怎么设置群消息关键词提醒呢？好像只能一股脑的全部转发了

### ISSUE THREAD

**Issue by JmsWang** [yzqzy/wechat-assistant#3]
#### Describe the problem you confuse
谢谢大佬

**Comment by yzqzy** [comment]
目前没处理这个功能，是想触发某个关键词（关键词位置在哪）才转发？是文本消息吗？还是所有消息都需要支持。

**Comment by yzqzy** [comment]
![image](https://github.com/yzqzy/wechat-assistant/assets/96212026/99ce0b09-dd31-4b3f-b0f2-8430855f3bc9)

最新版本已支持设置关键词触发，仅对任务转发类型和文本类型生效。

**Comment by friendbookok** [comment]
> ![image](https://private-user-images.githubusercontent.com/96212026/306529876-99ce0b09-dd31-4b3f-b0f2-8430855f3bc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1NzY1MzQsIm5iZiI6MTczMzU3NjIzNCwicGF0aCI6Ii85NjIxMjAyNi8zMDY1Mjk4NzYtOTljZTBiMDktZGQzMS00YjNmLWIwZjItODQzMDg1NWYzYmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA3VDEyNTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YjA5M2IxNjgxYzkyZTY1NDk5YjJkNWNjMWNjMWU1NTViZGY1OGJkNTgyYTc2M2ZlOGRiYjliNjZjMzliYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wBTH_vgoTQtJxYe8U7hXwYTEsyFlN7S8sbyf-RT_9sA)
> 
> 最新版本已支持设置关键词触发，仅对任务转发类型和文本类型生效。

经测试，不管是填写关键字还是没填写，都没有触发。用的是wxhelper-3.9.8.25.dll版本测试的
![image](https://github.com/user-attachments/assets/7c0066c9-98ce-4f60-81d5-5a5d79f6a98c)
