### ISSUE TITLE
请问微信版本正确注入闪退是什么问题[Help] the title of help wanted report

### ISSUE THREAD

**Issue by Hang-Y** [yzqzy/wechat-assistant#4]

**Comment by yzqzy** [comment]
本项目只是一个管理工具，项目中提供的是 64 位 dll，不能保证兼容所有平台，关于更多注入闪退问题，可以看下 [这个](
https://github.com/ttttupup/wxhelper/discussions/65) 。

64 位，我测试偶尔也会闪退一次，重新启动微信注入就正常了，不影响正常使用。
