### ISSUE TITLE
[Help] 3.8.1.26在gui里直接调用injector提示注入成功，但是不能跳转主页

### ISSUE THREAD

**Issue by mxdlzg** [yzqzy/wechat-assistant#7]
#### Describe the problem you confuse
用的3.8.1.26的wxhelper.dll（2年前release的那个）
32位的injector
![image](https://github.com/yzqzy/wechat-assistant/assets/18144577/a142aec9-d8af-41cd-af8b-a600e30b64f3)
可以看到dll注入成功
![image](https://github.com/yzqzy/wechat-assistant/assets/18144577/e847ceaa-6385-4189-967f-028a148fed14)

**Comment by yzqzy** [comment]
目前只支持 **3.9.5.81**，别的版本的 api 接口应该不一样。
