### ISSUE TITLE
[help] npm i 报错

### ISSUE THREAD

**Issue by lmuiotctf** [yzqzy/wechat-assistant#8]
#### Describe the problem you confuse
../node_modules/electron postinstall$ node install.js
│ RequestError: certificate has expired
│     at ClientRequest.<anonymous> (D:\1\Injector_x86_amd64_arm64\wechat-assistant\node_modules\.pnpm\got@11.8.6\node_modules\got\dist\source\  
│     at Object.onceWrapper (node:events:628:26)
│     at ClientRequest.emit (node:events:525:35)
│     at ClientRequest.origin.emit (D:\1\Injector_x86_amd64_arm64\wechat-assistant\node_modules\.pnpm\@szmarczak+http-timer@4.0.6\node_modules  
│     at TLSSocket.socketErrorListener (node:_http_client:494:9)
│     at TLSSocket.emit (node:events:513:28)
│     at emitErrorNT (node:internal/streams/destroy:157:8)
│     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21)
│     at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)
│     at TLSSocket.emit (node:events:513:28)
│     at TLSSocket._finishInit (node:_tls_wrap:953:8)
│     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12)

**Comment by yzqzy** [comment]
安装 electron 的问题，具体可以看这个 [issue](https://github.com/electron/electron/issues/41089)。
