### ISSUE TITLE
[Bug] 注入微信3.9.5.81后崩溃

### ISSUE THREAD

**Issue by luestr** [yzqzy/wechat-assistant#9]
#### Describe the bug
微信版本：3.9.5.81
wxhelper版本：3.9.8.25-v2
Injector版本：v1.4.0 x64

<img width="891" alt="Snipaste_2024-04-01_10-57-52" src="https://github.com/yzqzy/wechat-assistant/assets/152216177/0d027dee-c4d5-4468-8263-3e733b13e29d">

<img width="413" alt="Snipaste_2024-04-01_10-59-03" src="https://github.com/yzqzy/wechat-assistant/assets/152216177/0a5df60b-e506-448a-957b-836448b40923">

**Comment by yzqzy** [comment]
该项目只是管理工具，提供的是 64 位 dll，不能保证兼容所有平台，更多注入闪退问题，可以看下这个 [issue](https://github.com/ttttupup/wxhelper/discussions/65) 。
